stages:
  preprocess:
    cmd: python -m training preprocess
    deps:
      - src/training
      - src/common
      - data/raw
    params:
      - preprocess
    out:
      - data/processed

  train:
    cmd: python -m training train
    deps:
      - src/training
      - src/common
      - data/processed
    params:
      - model
      - training
    out:
      - models
    metrics:
      - metrics/train_metrics.json

  evaluate:
    cmd: python -m training evaluate
    deps:
      - models
      - data/processed
    params:
      - evaluate
    metrics:
      - metrics/eval_metrics.json
    plots:
      - metrics/eval_metrics.json:
          x: threshold
          y: [precision, recall]